# Generated by Django 5.0.1 on 2024-01-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIVIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('facultyid', models.IntegerField()),
                ('TimeSlot', models.CharField(max_length=50)),
                ('subjectid', models.CharField(max_length=10)),
                ('studentid', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='COUNCELLING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=10)),
                ('reportdate', models.DateField()),
                ('councellingno', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CSBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('facultyid', models.IntegerField()),
                ('TimeSlot', models.CharField(max_length=50)),
                ('subjectid', models.CharField(max_length=10)),
                ('studentid', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('facultyid', models.IntegerField()),
                ('TimeSlot', models.CharField(max_length=50)),
                ('subjectid', models.CharField(max_length=10)),
                ('studentid', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('facultyid', models.IntegerField()),
                ('TimeSlot', models.CharField(max_length=50)),
                ('subjectid', models.CharField(max_length=10)),
                ('studentid', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('facultyid', models.IntegerField()),
                ('TimeSlot', models.CharField(max_length=50)),
                ('subjectid', models.CharField(max_length=10)),
                ('studentid', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ECE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('facultyid', models.IntegerField()),
                ('TimeSlot', models.CharField(max_length=50)),
                ('subjectid', models.CharField(max_length=10)),
                ('studentid', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('facultyid', models.IntegerField()),
                ('TimeSlot', models.CharField(max_length=50)),
                ('subjectid', models.CharField(max_length=10)),
                ('studentid', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FACULTY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyid', models.IntegerField()),
                ('subjectid', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=1)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FACULTYMAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyid', models.IntegerField()),
                ('facultyname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MECH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('facultyid', models.IntegerField()),
                ('TimeSlot', models.CharField(max_length=50)),
                ('subjectid', models.CharField(max_length=10)),
                ('studentid', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SUBJECTMAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectid', models.CharField(max_length=10)),
                ('subjectname', models.CharField(max_length=40)),
            ],
        ),
    ]
