# Generated by Django 4.2.7 on 2024-01-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mansys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENTDETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=10)),
                ('reportdate', models.DateField()),
                ('councellingno', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('startdate', models.DateField()),
                ('branch', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='COUNCELLING',
        ),
        migrations.DeleteModel(
            name='FACULTYMAP',
        ),
        migrations.DeleteModel(
            name='SUBJECTMAP',
        ),
        migrations.RenameField(
            model_name='civil',
            old_name='TimeSlot',
            new_name='timeslot',
        ),
        migrations.RenameField(
            model_name='csbs',
            old_name='TimeSlot',
            new_name='timeslot',
        ),
        migrations.RenameField(
            model_name='csd',
            old_name='TimeSlot',
            new_name='timeslot',
        ),
        migrations.RenameField(
            model_name='cse',
            old_name='TimeSlot',
            new_name='Timeslot',
        ),
        migrations.RenameField(
            model_name='csm',
            old_name='TimeSlot',
            new_name='timeslot',
        ),
        migrations.RenameField(
            model_name='ece',
            old_name='TimeSlot',
            new_name='Timeslot',
        ),
        migrations.RenameField(
            model_name='eee',
            old_name='TimeSlot',
            new_name='timeslot',
        ),
        migrations.RenameField(
            model_name='mech',
            old_name='TimeSlot',
            new_name='timeslot',
        ),
        migrations.AddField(
            model_name='civil',
            name='subjectname',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='csbs',
            name='subjectname',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='csd',
            name='subjectname',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='cse',
            name='subjectname',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='csm',
            name='subjectname',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='ece',
            name='subjectname',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='eee',
            name='subjectname',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='numberclass',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='mech',
            name='subjectname',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='civil',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='csbs',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='csd',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cse',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ece',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eee',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mech',
            name='date',
            field=models.DateField(),
        ),
    ]
