# Generated by Django 5.0.1 on 2024-01-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mansys', '0002_studentdetails_delete_councelling_delete_facultymap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='branch',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
