# Generated by Django 3.1.2 on 2024-01-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mansys', '0004_auto_20240113_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='civil',
            old_name='timeslot',
            new_name='Timeslot',
        ),
        migrations.RenameField(
            model_name='csbs',
            old_name='timeslot',
            new_name='Timeslot',
        ),
        migrations.RenameField(
            model_name='csd',
            old_name='timeslot',
            new_name='Timeslot',
        ),
        migrations.RenameField(
            model_name='csm',
            old_name='timeslot',
            new_name='Timeslot',
        ),
        migrations.RenameField(
            model_name='eee',
            old_name='timeslot',
            new_name='Timeslot',
        ),
        migrations.RenameField(
            model_name='mech',
            old_name='timeslot',
            new_name='Timeslot',
        ),
    ]
