# Generated by Django 5.0.1 on 2024-01-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='NA', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='NA', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
